# -*- coding: utf-8 -*-
"""ANM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lMSQO2k-3VNOaYwkY4PhlCsVH81MzKGw
"""

import math

# ─────────────────────────────────────────────
#  Bisection Method — Applied Numerical Methods
# ─────────────────────────────────────────────

def f(x):
    """
    Define your function here.
    Change this to any equation you want to solve (= 0).

    Examples:
        return x**3 - x - 2
        return math.cos(x) - x
        return x**2 - 2
        return math.exp(x) - 3*x
    """
    return x**3 - x - 2


def bisection(a, b, tol, max_iter=50, criterion="interval"):
    """
    Bisection Method to find root of f(x) = 0 in [a, b].

    Parameters:
        a         : lower bound of interval
        b         : upper bound of interval
        tol       : tolerance (stopping condition)
        max_iter  : maximum number of iterations (default 50)
        criterion : stopping criterion
                    'interval' → |b - a| < tol
                    'fx'       → |f(c)| < tol
                    'both'     → both conditions met

    Returns:
        root      : approximate root
        iterations: number of iterations performed
    """

    fa = f(a)
    fb = f(b)

    # ── Pre-checks ──────────────────────────────
    if fa * fb > 0:
        print("\n  ERROR: f(a) and f(b) must have opposite signs.")
        print(f"  f({a}) = {fa:.6f}")
        print(f"  f({b}) = {fb:.6f}")
        print("  No guaranteed root in this interval.\n")
        return None, 0

    if fa == 0:
        print(f"\n  f(a) = 0 exactly. Root is a = {a}")
        return a, 0

    if fb == 0:
        print(f"\n  f(b) = 0 exactly. Root is b = {b}")
        return b, 0

    # ── Table Header ─────────────────────────────
    print("\n" + "=" * 90)
    print("  BISECTION METHOD")
    print("=" * 90)
    print(f"  Interval  : [{a}, {b}]")
    print(f"  f(a)      : {fa:.6f}")
    print(f"  f(b)      : {fb:.6f}")
    print(f"  Tolerance : {tol}")
    print(f"  Criterion : {criterion}")
    print(f"  Max Iter  : {max_iter}")
    print("=" * 90)
    print(f"{'Iter':>4}  {'a':>12}  {'b':>12}  {'c=(a+b)/2':>14}  "
          f"{'f(a)':>12}  {'f(c)':>12}  {'|b-a|':>12}  {'Error≈':>12}")
    print("-" * 90)

    root = None
    n    = 0

    for i in range(1, max_iter + 1):
        n  = i
        c  = (a + b) / 2.0
        fa = f(a)
        fc = f(c)
        interval_width = abs(b - a)
        error          = interval_width / 2.0

        print(f"{i:>4}  {a:>12.6f}  {b:>12.6f}  {c:>14.8f}  "
              f"{fa:>12.6f}  {fc:>12.6f}  {interval_width:>12.8f}  {error:>12.8f}")

        # ── Stopping Criteria ───────────────────
        if criterion == "interval":
            converged = interval_width < tol
        elif criterion == "fx":
            converged = abs(fc) < tol
        else:  # both
            converged = interval_width < tol and abs(fc) < tol

        if converged:
            root = c
            break

        # ── Update Bracket ──────────────────────
        if fa * fc < 0:
            b = c
        else:
            a = c

        root = c  # best estimate so far

    return root, n


def get_criterion():
    print("\n  Stopping criterion options:")
    print("    1 → |b - a| < tolerance  (interval width)")
    print("    2 → |f(c)| < tolerance   (function value)")
    print("    3 → Both conditions")
    choice = input("  Choose [1/2/3] (default 1): ").strip()
    return {"2": "fx", "3": "both"}.get(choice, "interval")


def main():
    print("\n" + "━" * 90)
    print("  BISECTION METHOD SOLVER — Applied Numerical Methods")
    print("━" * 90)
    print("  Current function: f(x) = x³ - x - 2")
    print("  (Edit the f(x) function in this file to change it)\n")

    # ── User Inputs ──────────────────────────────
    try:
        a       = float(input("  Enter lower bound a: "))
        b       = float(input("  Enter upper bound b: "))
        tol     = float(input("  Enter tolerance ε (e.g. 0.001): "))
        max_it  = input("  Max iterations (default 50): ").strip()
        max_it  = int(max_it) if max_it else 50
    except ValueError:
        print("\n  ERROR: Invalid input. Please enter numeric values.\n")
        return

    criterion = get_criterion()

    # ── Run Solver ───────────────────────────────
    root, iters = bisection(a, b, tol, max_it, criterion)

    # ── Final Summary ─────────────────────────────
    print("-" * 90)
    if root is not None:
        print("\n  ╔══════════════════════════════════════╗")
        print(f"  ║  Approximate Root  : {root:.8f}      ║")
        print(f"  ║  f(root)           : {f(root):.2e}          ║")
        print(f"  ║  Iterations used   : {iters:<4}                ║")
        print(f"  ║  Tolerance         : {tol}               ║")
        print("  ╚══════════════════════════════════════╝\n")
    else:
        print("\n  No root found. Check your interval and function.\n")


if __name__ == "__main__":
    main()

import math

# ─────────────────────────────────────────────────────
#  Fixed Point Iteration Method — Applied Numerical Methods
# ─────────────────────────────────────────────────────
#
#  Solves f(x) = 0 by rewriting as x = g(x)
#  Then iterating:  x_(n+1) = g(x_n)
#
#  Convergence condition: |g'(x)| < 1 near the root
# ─────────────────────────────────────────────────────


def g(x):
    """
    Iteration function g(x) such that f(x) = 0 ⟺ x = g(x)

    Change this to match your equation.

    Examples (equation → rearranged g(x)):
        f(x) = x³ - x - 2         →  g(x) = (x + 2) ** (1/3)
        f(x) = cos(x) - x         →  g(x) = math.cos(x)
        f(x) = x² - 2             →  g(x) = 2 / x          (or (x + 2/x)/2 for Newton-like)
        f(x) = e^x - 3x           →  g(x) = math.exp(x) / 3
        f(x) = x³ - 4x + 1       →  g(x) = (x**3 + 1) / 4
    """
    return (x + 2) ** (1/3)


def f(x):
    """
    Original equation f(x) = 0
    Used only to display f(x_n) in the table for verification.
    Change this to match your equation.
    """
    return x**3 - x - 2


def fixed_point_iteration(x0, tol, max_iter=50, criterion="both"):
    """
    Fixed Point Iteration to find root of f(x) = 0
    by solving x = g(x).

    Parameters:
        x0        : initial guess
        tol       : tolerance (stopping condition)
        max_iter  : maximum number of iterations (default 50)
        criterion : stopping criterion
                    'absolute' → |x_(n+1) - x_n| < tol
                    'relative' → |x_(n+1) - x_n| / |x_(n+1)| < tol
                    'fx'       → |f(x_n)| < tol
                    'both'     → |x_(n+1) - x_n| < tol AND |f(x_n)| < tol

    Returns:
        root       : approximate root
        iterations : number of iterations performed
    """

    # ── Table Header ─────────────────────────────
    print("\n" + "=" * 95)
    print("  FIXED POINT ITERATION METHOD")
    print("=" * 95)
    print(f"  Initial Guess : x0 = {x0}")
    print(f"  g(x0)         : {g(x0):.8f}")
    print(f"  f(x0)         : {f(x0):.8f}")
    print(f"  Tolerance     : {tol}")
    print(f"  Criterion     : {criterion}")
    print(f"  Max Iter      : {max_iter}")
    print("=" * 95)
    print(f"{'Iter':>4}  {'x_n':>14}  {'x_(n+1)=g(x_n)':>16}  "
          f"{'f(x_n)':>12}  {'|x_(n+1)-x_n|':>14}  {'Rel. Error':>12}  {'Status':>10}")
    print("-" * 95)

    x_n   = x0
    root  = None
    iters = 0

    for i in range(1, max_iter + 1):
        iters = i

        try:
            x_next = g(x_n)
        except (ValueError, ZeroDivisionError, OverflowError) as e:
            print(f"\n  ERROR at iteration {i}: g(x) undefined — {e}")
            print("  Try a different initial guess or rewrite g(x).\n")
            return None, i

        fx_n      = f(x_n)
        abs_err   = abs(x_next - x_n)
        rel_err   = abs_err / abs(x_next) if abs(x_next) > 1e-12 else float('inf')

        # ── Divergence check ────────────────────
        if abs(x_next) > 1e10:
            status = "DIVERGED"
            print(f"{i:>4}  {x_n:>14.8f}  {x_next:>16.8f}  "
                  f"{fx_n:>12.6f}  {abs_err:>14.8f}  {rel_err:>12.6e}  {status:>10}")
            print("\n  ✗ Method is DIVERGING. Try a different g(x) or initial guess.\n")
            return None, i

        # ── Stopping Criteria ───────────────────
        if criterion == "absolute":
            converged = abs_err < tol
        elif criterion == "relative":
            converged = rel_err < tol
        elif criterion == "fx":
            converged = abs(fx_n) < tol
        else:  # both
            converged = abs_err < tol and abs(f(x_next)) < tol

        status = "✓ DONE" if converged else ""

        print(f"{i:>4}  {x_n:>14.8f}  {x_next:>16.8f}  "
              f"{fx_n:>12.6f}  {abs_err:>14.8f}  {rel_err:>12.6e}  {status:>10}")

        if converged:
            root = x_next
            break

        x_n = x_next
        root = x_next  # best estimate so far

    return root, iters


def get_criterion():
    print("\n  Stopping criterion options:")
    print("    1 → |x_(n+1) - x_n| < tolerance         (absolute error)")
    print("    2 → |x_(n+1) - x_n| / |x_(n+1)| < tol  (relative error)")
    print("    3 → |f(x_n)| < tolerance                 (function value)")
    print("    4 → Both absolute error AND |f(x)| < tol")
    choice = input("  Choose [1/2/3/4] (default 4): ").strip()
    return {"1": "absolute", "2": "relative", "3": "fx"}.get(choice, "both")


def main():
    print("\n" + "━" * 95)
    print("  FIXED POINT ITERATION SOLVER — Applied Numerical Methods")
    print("━" * 95)
    print("  Current equation : f(x) = x³ - x - 2  →  x = g(x) = (x + 2)^(1/3)")
    print("  (Edit f(x) and g(x) functions in this file to change the equation)\n")

    # ── User Inputs ──────────────────────────────
    try:
        x0     = float(input("  Enter initial guess x0: "))
        tol    = float(input("  Enter tolerance ε (e.g. 0.0001): "))
        max_it = input("  Max iterations (default 50): ").strip()
        max_it = int(max_it) if max_it else 50
    except ValueError:
        print("\n  ERROR: Invalid input. Please enter numeric values.\n")
        return

    criterion = get_criterion()

    # ── Run Solver ───────────────────────────────
    root, iters = fixed_point_iteration(x0, tol, max_it, criterion)

    # ── Final Summary ─────────────────────────────
    print("-" * 95)
    if root is not None:
        print("\n  ╔══════════════════════════════════════════╗")
        print(f"  ║  Approximate Root  : {root:.8f}          ║")
        print(f"  ║  f(root)           : {f(root):.6e}          ║")
        print(f"  ║  g(root)           : {g(root):.8f}          ║")
        print(f"  ║  Iterations used   : {iters:<4}                  ║")
        print(f"  ║  Tolerance         : {tol}                 ║")
        print("  ╚══════════════════════════════════════════╝\n")
    else:
        print("\n  No root found. Suggestions:")
        print("  • Try a different initial guess x0")
        print("  • Rewrite g(x) so that |g'(x)| < 1 near the root")
        print("  • Increase max iterations\n")


if __name__ == "__main__":
    main()

import math

# ─────────────────────────────────────────────────────
#  Secant Method — Applied Numerical Methods
# ─────────────────────────────────────────────────────
#
#  Finds root of f(x) = 0 using two initial guesses.
#  Does NOT require derivative of f(x).
#
#  Formula:
#      x_(n+1) = x_n - f(x_n) * (x_n - x_(n-1))
#                              / (f(x_n) - f(x_(n-1)))
#
#  Convergence order: ~1.618 (superlinear)
# ─────────────────────────────────────────────────────


def f(x):
    """
    Define your function f(x) here.
    The method finds x such that f(x) = 0.

    Examples:
        return x**3 - x - 2
        return math.cos(x) - x
        return x**2 - 2
        return math.exp(x) - 3*x
        return x**3 - 4*x + 1
        return math.log(x) - math.cos(x)
    """
    return x**3 - x - 2


def secant(x0, x1, tol, max_iter=50, criterion="both"):
    """
    Secant Method to find root of f(x) = 0.

    Parameters:
        x0        : first initial guess
        x1        : second initial guess
        tol       : tolerance (stopping condition)
        max_iter  : maximum number of iterations (default 50)
        criterion : stopping criterion
                    'absolute' → |x_(n+1) - x_n| < tol
                    'relative' → |x_(n+1) - x_n| / |x_(n+1)| < tol
                    'fx'       → |f(x_(n+1))| < tol
                    'both'     → absolute error AND |f(x)| < tol

    Returns:
        root       : approximate root
        iterations : number of iterations performed
    """

    f0 = f(x0)
    f1 = f(x1)

    # ── Table Header ─────────────────────────────
    print("\n" + "=" * 100)
    print("  SECANT METHOD")
    print("=" * 100)
    print(f"  First guess   x0 = {x0}   →  f(x0) = {f0:.8f}")
    print(f"  Second guess  x1 = {x1}   →  f(x1) = {f1:.8f}")
    print(f"  Tolerance        : {tol}")
    print(f"  Criterion        : {criterion}")
    print(f"  Max Iterations   : {max_iter}")
    print("=" * 100)
    print(f"{'Iter':>4}  {'x_(n-1)':>14}  {'x_n':>14}  {'x_(n+1)':>14}  "
          f"{'f(x_n)':>12}  {'f(x_(n+1))':>12}  {'|x_(n+1)-x_n|':>14}  {'Status':>8}")
    print("-" * 100)

    # Print iteration 0 as starting state
    print(f"{'0':>4}  {'—':>14}  {x0:>14.8f}  {x1:>14.8f}  "
          f"{f0:>12.6f}  {f1:>12.6f}  {'—':>14}  {'':>8}")

    root  = None
    iters = 0

    x_prev = x0
    x_curr = x1

    for i in range(1, max_iter + 1):
        iters = i

        f_prev = f(x_prev)
        f_curr = f(x_curr)

        # ── Denominator check ────────────────────
        denom = f_curr - f_prev
        if abs(denom) < 1e-14:
            print(f"\n  ERROR at iteration {i}: f(x_n) - f(x_(n-1)) ≈ 0")
            print("  Division by zero encountered. Try different initial guesses.\n")
            return None, i

        # ── Secant formula ───────────────────────
        x_next = x_curr - f_curr * (x_curr - x_prev) / denom
        f_next = f(x_next)

        abs_err = abs(x_next - x_curr)
        rel_err = abs_err / abs(x_next) if abs(x_next) > 1e-12 else float('inf')

        # ── Divergence check ─────────────────────
        if abs(x_next) > 1e10 or math.isnan(x_next) or math.isinf(x_next):
            print(f"{i:>4}  {x_prev:>14.8f}  {x_curr:>14.8f}  {x_next:>14.4e}  "
                  f"{f_curr:>12.6f}  {f_next:>12.4e}  {abs_err:>14.4e}  {'DIVERGED':>8}")
            print("\n  ✗ Method is DIVERGING. Try different initial guesses.\n")
            return None, i

        # ── Stopping Criteria ────────────────────
        if criterion == "absolute":
            converged = abs_err < tol
        elif criterion == "relative":
            converged = rel_err < tol
        elif criterion == "fx":
            converged = abs(f_next) < tol
        else:  # both
            converged = abs_err < tol and abs(f_next) < tol

        status = "✓ DONE" if converged else ""

        print(f"{i:>4}  {x_prev:>14.8f}  {x_curr:>14.8f}  {x_next:>14.8f}  "
              f"{f_curr:>12.6f}  {f_next:>12.6f}  {abs_err:>14.8f}  {status:>8}")

        if converged:
            root = x_next
            break

        x_prev = x_curr
        x_curr = x_next
        root   = x_next  # best estimate so far

    return root, iters


def get_criterion():
    print("\n  Stopping criterion options:")
    print("    1 → |x_(n+1) - x_n| < tolerance         (absolute error)")
    print("    2 → |x_(n+1) - x_n| / |x_(n+1)| < tol  (relative error)")
    print("    3 → |f(x_(n+1))| < tolerance             (function value)")
    print("    4 → Both absolute error AND |f(x)| < tol")
    choice = input("  Choose [1/2/3/4] (default 4): ").strip()
    return {"1": "absolute", "2": "relative", "3": "fx"}.get(choice, "both")


def main():
    print("\n" + "━" * 100)
    print("  SECANT METHOD SOLVER — Applied Numerical Methods")
    print("━" * 100)
    print("  Current function : f(x) = x³ - x - 2")
    print("  (Edit the f(x) function in this file to change the equation)\n")

    # ── User Inputs ──────────────────────────────
    try:
        x0     = float(input("  Enter first initial guess  x0: "))
        x1     = float(input("  Enter second initial guess x1: "))
        tol    = float(input("  Enter tolerance ε (e.g. 0.0001): "))
        max_it = input("  Max iterations (default 50): ").strip()
        max_it = int(max_it) if max_it else 50
    except ValueError:
        print("\n  ERROR: Invalid input. Please enter numeric values.\n")
        return

    criterion = get_criterion()

    # ── Run Solver ───────────────────────────────
    root, iters = secant(x0, x1, tol, max_it, criterion)

    # ── Final Summary ─────────────────────────────
    print("-" * 100)
    if root is not None:
        print("\n  ╔══════════════════════════════════════════╗")
        print(f"  ║  Approximate Root  : {root:.8f}          ║")
        print(f"  ║  f(root)           : {f(root):.6e}          ║")
        print(f"  ║  Iterations used   : {iters:<4}                  ║")
        print(f"  ║  Tolerance         : {tol}                 ║")
        print("  ╚══════════════════════════════════════════╝\n")
    else:
        print("\n  No root found. Suggestions:")
        print("  • Try different initial guesses x0 and x1")
        print("  • Ensure x0 ≠ x1 and f(x0) ≠ f(x1)")
        print("  • Choose guesses closer to the expected root")
        print("  • Increase max iterations\n")


if __name__ == "__main__":
    main()

import math

# ─────────────────────────────────────────────────────────────────
#  Newton's Interpolation Method — Applied Numerical Methods
#  Covers:
#    1. Newton's Forward Difference Interpolation
#    2. Newton's Backward Difference Interpolation
# ─────────────────────────────────────────────────────────────────
#
#  Forward  formula (use when x is near the BEGINNING of the table)
#  Backward formula (use when x is near the END of the table)
#
#  Both use equally spaced data points.
# ─────────────────────────────────────────────────────────────────


# ══════════════════════════════════════════════════════════════════
#  DIFFERENCE TABLE
# ══════════════════════════════════════════════════════════════════

def build_difference_table(y):
    """
    Builds the full finite difference table from y values.
    Returns a 2D list where diff[i][j] = j-th order difference at index i.
    diff[i][0] = y[i]
    """
    n = len(y)
    diff = [[0.0] * n for _ in range(n)]

    for i in range(n):
        diff[i][0] = y[i]

    for j in range(1, n):
        for i in range(n - j):
            diff[i][j] = diff[i + 1][j - 1] - diff[i][j - 1]

    return diff


def print_difference_table(x, y, diff):
    """Prints the forward difference table in a neat format."""
    n = len(x)
    h = x[1] - x[0]

    print("\n" + "=" * (16 * (n + 1)))
    print("  FORWARD DIFFERENCE TABLE")
    print("=" * (16 * (n + 1)))

    # Header
    header = f"{'x':>10}  {'y = f(x)':>12}"
    for j in range(1, n):
        header += f"  {'Δ' * j + 'y':>12}"
    print(header)
    print("-" * (16 * (n + 1)))

    # Rows
    for i in range(n):
        row = f"  {x[i]:>8.4f}  {diff[i][0]:>12.6f}"
        for j in range(1, n - i):
            row += f"  {diff[i][j]:>12.6f}"
        print(row)

    print("=" * (16 * (n + 1)))


# ══════════════════════════════════════════════════════════════════
#  FORWARD INTERPOLATION
# ══════════════════════════════════════════════════════════════════

def newton_forward(x, y, x_val):
    """
    Newton's Forward Difference Interpolation.
    Best used when x_val is near the START of the table.

    Formula:
        y(x) = y0 + s*Δy0 + s(s-1)/2! * Δ²y0 + ...
        where s = (x - x0) / h
    """
    n    = len(x)
    h    = x[1] - x[0]
    diff = build_difference_table(y)

    x0 = x[0]
    s  = (x_val - x0) / h

    print("\n" + "─" * 60)
    print("  NEWTON'S FORWARD INTERPOLATION")
    print("─" * 60)
    print(f"  x0 = {x0},  h = {h},  x = {x_val}")
    print(f"  s  = (x - x0) / h = ({x_val} - {x0}) / {h} = {s:.6f}")
    print("─" * 60)
    print(f"  {'Term':>4}  {'Δⁿy₀':>14}  {'s-factor':>20}  {'Contribution':>14}")
    print("  " + "-" * 56)

    result    = diff[0][0]
    s_factor  = 1.0
    factorial = 1.0

    print(f"  {'0':>4}  {diff[0][0]:>14.6f}  {'1':>20}  {diff[0][0]:>14.6f}")

    for k in range(1, n):
        s_factor  *= (s - (k - 1))
        factorial *= k
        term       = (s_factor / factorial) * diff[0][k]
        result    += term

        s_expr = f"s(s-1)...(s-{k-1})" if k > 1 else "s"
        print(f"  {k:>4}  {diff[0][k]:>14.6f}  {s_expr + f'/{k}!' :>20}  {term:>14.6f}")

    return result


# ══════════════════════════════════════════════════════════════════
#  BACKWARD INTERPOLATION
# ══════════════════════════════════════════════════════════════════

def newton_backward(x, y, x_val):
    """
    Newton's Backward Difference Interpolation.
    Best used when x_val is near the END of the table.

    Formula:
        y(x) = yn + s*∇yn + s(s+1)/2! * ∇²yn + ...
        where s = (x - xn) / h
    """
    n    = len(x)
    h    = x[1] - x[0]
    diff = build_difference_table(y)

    xn = x[n - 1]
    s  = (x_val - xn) / h

    print("\n" + "─" * 60)
    print("  NEWTON'S BACKWARD INTERPOLATION")
    print("─" * 60)
    print(f"  xn = {xn},  h = {h},  x = {x_val}")
    print(f"  s  = (x - xn) / h = ({x_val} - {xn}) / {h} = {s:.6f}")
    print("─" * 60)
    print(f"  {'Term':>4}  {'∇ⁿyₙ':>14}  {'s-factor':>20}  {'Contribution':>14}")
    print("  " + "-" * 56)

    result    = diff[n - 1][0]
    s_factor  = 1.0
    factorial = 1.0

    print(f"  {'0':>4}  {diff[n-1][0]:>14.6f}  {'1':>20}  {diff[n-1][0]:>14.6f}")

    for k in range(1, n):
        s_factor  *= (s + (k - 1))
        factorial *= k
        term       = (s_factor / factorial) * diff[n - 1 - k][k]
        result    += term

        s_expr = f"s(s+1)...(s+{k-1})" if k > 1 else "s"
        print(f"  {k:>4}  {diff[n-1-k][k]:>14.6f}  {s_expr + f'/{k}!':>20}  {term:>14.6f}")

    return result


# ══════════════════════════════════════════════════════════════════
#  VALIDATION
# ══════════════════════════════════════════════════════════════════

def validate_equal_spacing(x):
    """Checks that x values are equally spaced."""
    h = x[1] - x[0]
    for i in range(1, len(x) - 1):
        if abs((x[i + 1] - x[i]) - h) > 1e-9:
            return False, h
    return True, h


# ══════════════════════════════════════════════════════════════════
#  MAIN
# ══════════════════════════════════════════════════════════════════

def main():
    print("\n" + "━" * 70)
    print("  NEWTON'S INTERPOLATION — Applied Numerical Methods")
    print("━" * 70)
    print("  Supports: Forward & Backward Difference Interpolation")
    print("  Requirement: Equally spaced x values\n")

    # ── Input: number of data points ──────────────
    try:
        n = int(input("  Enter number of data points: "))
        if n < 2:
            print("  ERROR: Need at least 2 data points.")
            return
    except ValueError:
        print("  ERROR: Enter a valid integer.")
        return

    # ── Input: x and y values ─────────────────────
    print(f"\n  Enter {n} data points (x and y values):\n")
    x_data = []
    y_data = []

    for i in range(n):
        try:
            xi = float(input(f"    x[{i}] = "))
            yi = float(input(f"    y[{i}] = f({xi}) = "))
            x_data.append(xi)
            y_data.append(yi)
        except ValueError:
            print("  ERROR: Invalid input.")
            return

    # ── Validate equal spacing ────────────────────
    equal, h = validate_equal_spacing(x_data)
    if not equal:
        print("\n  ERROR: x values are NOT equally spaced.")
        print("  Newton's Forward/Backward method requires equal spacing.")
        print("  Use Lagrange or Divided Difference method for unequal spacing.\n")
        return

    print(f"\n  Step size h = {h}")

    # ── Print difference table ────────────────────
    diff = build_difference_table(y_data)
    print_difference_table(x_data, y_data, diff)

    # ── Input: interpolation point ────────────────
    try:
        x_val = float(input("\n  Enter x value to interpolate at: "))
    except ValueError:
        print("  ERROR: Invalid value.")
        return

    # ── Choose method ─────────────────────────────
    midpoint = (x_data[0] + x_data[-1]) / 2
    if x_val <= midpoint:
        auto = "Forward (x is in the first half of the table)"
    else:
        auto = "Backward (x is in the second half of the table)"

    print(f"\n  Auto-suggestion: {auto}")
    print("  Method options:")
    print("    1 → Newton's Forward Interpolation")
    print("    2 → Newton's Backward Interpolation")
    print("    3 → Both (compare results)")
    choice = input("  Choose [1/2/3] (default: auto-suggest): ").strip()

    if choice == "" :
        choice = "1" if x_val <= midpoint else "2"

    # ── Run ───────────────────────────────────────
    result_f = result_b = None

    if choice in ("1", "3"):
        result_f = newton_forward(x_data, y_data, x_val)

    if choice in ("2", "3"):
        result_b = newton_backward(x_data, y_data, x_val)

    # ── Final Summary ─────────────────────────────
    print("\n" + "=" * 70)
    print("  RESULT SUMMARY")
    print("=" * 70)
    print(f"  Interpolating at x = {x_val}")
    print(f"  Step size h        = {h}")
    print(f"  Data range         = [{x_data[0]}, {x_data[-1]}]")

    if result_f is not None:
        print(f"\n  ┌─────────────────────────────────────────────────┐")
        print(f"  │  Forward Interpolation  →  f({x_val}) ≈ {result_f:.6f}   │")
        print(f"  └─────────────────────────────────────────────────┘")

    if result_b is not None:
        print(f"\n  ┌─────────────────────────────────────────────────┐")
        print(f"  │  Backward Interpolation →  f({x_val}) ≈ {result_b:.6f}   │")
        print(f"  └─────────────────────────────────────────────────┘")

    if result_f is not None and result_b is not None:
        diff_val = abs(result_f - result_b)
        print(f"\n  Difference between methods : {diff_val:.2e}")
        print("  (Should be near zero for values within the table range)")

    print()


if __name__ == "__main__":
    main()4]57